project_id = "oltzgidkjxwsukvkomof"

[functions.invite-user]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.qr-redirect]
verify_jwt = false

[functions.validate-coc]
verify_jwt = true

[functions.extract-coc]
verify_jwt = false

[functions.validation-chat]
verify_jwt = true

[functions.send-email]
verify_jwt = true
