project_id = "oltzgidkjxwsukvkomof"

[functions.invite-user]
verify_jwt = true

[functions.qr-redirect]
verify_jwt = false

[functions.validate-coc]
verify_jwt = true

[functions.validation-chat]
verify_jwt = true
