
-- Add columns to support Annexure 1 COC form structure
ALTER TABLE public.coc_local_validations
  ADD COLUMN IF NOT EXISTS form_type text NOT NULL DEFAULT 'annexure1',
  ADD COLUMN IF NOT EXISTS form_data_json jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS building_name text,
  ADD COLUMN IF NOT EXISTS gps_coordinates text,
  ADD COLUMN IF NOT EXISTS suburb_township text,
  ADD COLUMN IF NOT EXISTS district_town_city text,
  ADD COLUMN IF NOT EXISTS erf_lot_no text,
  ADD COLUMN IF NOT EXISTS registered_person_id_number text,
  ADD COLUMN IF NOT EXISTS regulation_type text,
  ADD COLUMN IF NOT EXISTS registered_person_reg_date text,
  ADD COLUMN IF NOT EXISTS supply_system_type text DEFAULT 'TN-S',
  ADD COLUMN IF NOT EXISTS installation_permanent boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS phase_rotation text,
  ADD COLUMN IF NOT EXISTS main_switch_type text,
  ADD COLUMN IF NOT EXISTS number_of_poles integer,
  ADD COLUMN IF NOT EXISTS current_rating_a numeric,
  ADD COLUMN IF NOT EXISTS short_circuit_withstand_ka numeric,
  ADD COLUMN IF NOT EXISTS neutral_loop_impedance_ohm numeric,
  ADD COLUMN IF NOT EXISTS elevated_voltage_v numeric,
  ADD COLUMN IF NOT EXISTS voltage_no_load_r numeric,
  ADD COLUMN IF NOT EXISTS voltage_no_load_y numeric,
  ADD COLUMN IF NOT EXISTS voltage_no_load_b numeric,
  ADD COLUMN IF NOT EXISTS voltage_full_load_r numeric,
  ADD COLUMN IF NOT EXISTS voltage_full_load_y numeric,
  ADD COLUMN IF NOT EXISTS voltage_full_load_b numeric,
  ADD COLUMN IF NOT EXISTS continuity_of_bonding text,
  ADD COLUMN IF NOT EXISTS continuity_ring_circuits text,
  ADD COLUMN IF NOT EXISTS earth_leakage_test_button boolean,
  ADD COLUMN IF NOT EXISTS phase_rotation_correct boolean,
  ADD COLUMN IF NOT EXISTS switching_devices_correct boolean,
  ADD COLUMN IF NOT EXISTS comments text,
  ADD COLUMN IF NOT EXISTS db_supply_name text;
