// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oltzgidkjxwsukvkomof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9sdHpnaWRranh3c3VrdmtvbW9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0MTk3MjksImV4cCI6MjA3NTk5NTcyOX0.W5GbT2R2tpkl4-RHNJAnf29czP0tCXldgjdXC2-hMXI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});